### ISSUE TITLE
ld: library not found for -lgcc_s.10.4 when installing Numpy SciPy

### ISSUE THREAD

**Issue by Cactusolo** [jonchang/tact#2]
Hi,
I tried to install Numpy SciPy with pypy3, it gives me error:
1. ld: library not found for -lgcc_s.10.4
clang: error: linker command failed with exit code 1 (use -v to see invocation)
2. RuntimeError: Broken toolchain: cannot link a simple C program

BTW, I have run `pip_pypy3 install --upgrade pip setuptools `in the initial step. 
Appreciate any suggestions!

my running log is below:
Cactus:~ Miao$ easy_install_pypy3 Numpy SciPy
Searching for Numpy
Reading https://pypi.org/simple/Numpy/
Downloading https://files.pythonhosted.org/packages/cf/8d/6345b4f32b37945fedc1e027e83970005fc9c699068d2f566b82826515f2/numpy-1.16.2.zip#sha256=6c692e3879dde0b67a9dc78f9bfb6f61c666b4562fd8619632d7043fb5b691b0
Best match: numpy 1.16.2
Processing numpy-1.16.2.zip
Writing /var/folders/kv/1wctm3ys2yzd83zcngcpzlnw0000gn/T/easy_install-rn886pfq/numpy-1.16.2/setup.cfg
Running numpy-1.16.2/setup.py -q bdist_egg --dist-dir /var/folders/kv/1wctm3ys2yzd83zcngcpzlnw0000gn/T/easy_install-rn886pfq/numpy-1.16.2/egg-dist-tmp-37dchze3
Running from numpy source directory.
/var/folders/kv/1wctm3ys2yzd83zcngcpzlnw0000gn/T/easy_install-rn886pfq/numpy-1.16.2/setup.py:390: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
  run_build = parse_setuppy_commands()
non-existing path in 'numpy/distutils': 'site.cfg'
/usr/local/Cellar/pypy3/7.0.0/libexec/lib-python/3/distutils/dist.py:261: UserWarning: Unknown distribution option: 'define_macros'
  warnings.warn(msg)
/var/folders/kv/1wctm3ys2yzd83zcngcpzlnw0000gn/T/easy_install-rn886pfq/numpy-1.16.2/numpy/distutils/fcompiler/gnu.py:353: UserWarning: Env. variable MACOSX_DEPLOYMENT_TARGET set to 10.3
  flags = GnuFCompiler.get_flags_linker_so(self)
/var/folders/kv/1wctm3ys2yzd83zcngcpzlnw0000gn/T/easy_install-rn886pfq/numpy-1.16.2/numpy/distutils/fcompiler/__init__.py:530: UserWarning: LDFLAGS is used as is, not appended to flags already defined by numpy.distutils! Use NPY_DISTUTILS_APPEND_FLAGS=1 to obtain appending behavior instead (this behavior will become default in a future release).
  linker_so_flags = self.flag_vars.linker_so
/var/folders/kv/1wctm3ys2yzd83zcngcpzlnw0000gn/T/easy_install-rn886pfq/numpy-1.16.2/numpy/distutils/fcompiler/__init__.py:540: UserWarning: LDFLAGS is used as is, not appended to flags already defined by numpy.distutils! Use NPY_DISTUTILS_APPEND_FLAGS=1 to obtain appending behavior instead (this behavior will become default in a future release).
  linker_exe_flags = self.flag_vars.linker_exe
**ld: library not found for -lgcc_s.10.4
clang: error: linker command failed with exit code 1 (use -v to see invocation)**
Traceback (most recent call last):
  File "/usr/local/Cellar/pypy3/7.0.0/libexec/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/local/Cellar/pypy3/7.0.0/libexec/site-packages/setuptools/sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "/usr/local/Cellar/pypy3/7.0.0/libexec/site-packages/setuptools/sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File "/var/folders/kv/1wctm3ys2yzd83zcngcpzlnw0000gn/T/easy_install-rn886pfq/numpy-1.16.2/setup.py", line 415, in <module>
  File "/var/folders/kv/1wctm3ys2yzd83zcngcpzlnw0000gn/T/easy_install-rn886pfq/numpy-1.16.2/setup.py", line 407, in setup_package
  File "/var/folders/kv/1wctm3ys2yzd83zcngcpzlnw0000gn/T/easy_install-rn886pfq/numpy-1.16.2/numpy/distutils/core.py", line 171, in setup
  File "/usr/local/Cellar/pypy3/7.0.0/libexec/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/usr/local/Cellar/pypy3/7.0.0/libexec/lib-python/3/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/local/Cellar/pypy3/7.0.0/libexec/lib-python/3/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/local/Cellar/pypy3/7.0.0/libexec/lib-python/3/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/local/Cellar/pypy3/7.0.0/libexec/site-packages/setuptools/command/bdist_egg.py", line 163, in run
    self.run_command("egg_info")
  File "/usr/local/Cellar/pypy3/7.0.0/libexec/lib-python/3/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/local/Cellar/pypy3/7.0.0/libexec/lib-python/3/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/var/folders/kv/1wctm3ys2yzd83zcngcpzlnw0000gn/T/easy_install-rn886pfq/numpy-1.16.2/numpy/distutils/command/egg_info.py", line 26, in run
  File "/usr/local/Cellar/pypy3/7.0.0/libexec/lib-python/3/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/local/Cellar/pypy3/7.0.0/libexec/lib-python/3/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/var/folders/kv/1wctm3ys2yzd83zcngcpzlnw0000gn/T/easy_install-rn886pfq/numpy-1.16.2/numpy/distutils/command/build_src.py", line 148, in run
  File "/var/folders/kv/1wctm3ys2yzd83zcngcpzlnw0000gn/T/easy_install-rn886pfq/numpy-1.16.2/numpy/distutils/command/build_src.py", line 159, in build_sources
  File "/var/folders/kv/1wctm3ys2yzd83zcngcpzlnw0000gn/T/easy_install-rn886pfq/numpy-1.16.2/numpy/distutils/command/build_src.py", line 292, in build_library_sources
  File "/var/folders/kv/1wctm3ys2yzd83zcngcpzlnw0000gn/T/easy_install-rn886pfq/numpy-1.16.2/numpy/distutils/command/build_src.py", line 375, in generate_sources
  File "numpy/core/setup.py", line 667, in get_mathlib_info
RuntimeError: Broken toolchain: cannot link a simple C program

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/easy_install_pypy3", line 11, in <module>
    sys.exit(main())
  File "/usr/local/Cellar/pypy3/7.0.0/libexec/site-packages/setuptools/command/easy_install.py", line 2316, in main
    **kw
  File "/usr/local/Cellar/pypy3/7.0.0/libexec/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/usr/local/Cellar/pypy3/7.0.0/libexec/lib-python/3/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/local/Cellar/pypy3/7.0.0/libexec/lib-python/3/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/local/Cellar/pypy3/7.0.0/libexec/lib-python/3/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/local/Cellar/pypy3/7.0.0/libexec/site-packages/setuptools/command/easy_install.py", line 418, in run
    self.easy_install(spec, not self.no_deps)
  File "/usr/local/Cellar/pypy3/7.0.0/libexec/site-packages/setuptools/command/easy_install.py", line 679, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/usr/local/Cellar/pypy3/7.0.0/libexec/site-packages/setuptools/command/easy_install.py", line 705, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/usr/local/Cellar/pypy3/7.0.0/libexec/site-packages/setuptools/command/easy_install.py", line 890, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/usr/local/Cellar/pypy3/7.0.0/libexec/site-packages/setuptools/command/easy_install.py", line 1158, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/usr/local/Cellar/pypy3/7.0.0/libexec/site-packages/setuptools/command/easy_install.py", line 1144, in run_setup
    run_setup(setup_script, args)
  File "/usr/local/Cellar/pypy3/7.0.0/libexec/site-packages/setuptools/sandbox.py", line 253, in run_setup
    raise
  File "/usr/local/Cellar/pypy3/7.0.0/libexec/lib-python/3/contextlib.py", line 100, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/Cellar/pypy3/7.0.0/libexec/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/local/Cellar/pypy3/7.0.0/libexec/lib-python/3/contextlib.py", line 100, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/Cellar/pypy3/7.0.0/libexec/site-packages/setuptools/sandbox.py", line 166, in save_modules
    saved_exc.resume()
  File "/usr/local/Cellar/pypy3/7.0.0/libexec/site-packages/setuptools/sandbox.py", line 141, in resume
    six.reraise(type, exc, self._tb)
  File "/usr/local/Cellar/pypy3/7.0.0/libexec/site-packages/setuptools/_vendor/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/Cellar/pypy3/7.0.0/libexec/site-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/usr/local/Cellar/pypy3/7.0.0/libexec/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/local/Cellar/pypy3/7.0.0/libexec/site-packages/setuptools/sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "/usr/local/Cellar/pypy3/7.0.0/libexec/site-packages/setuptools/sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File "/var/folders/kv/1wctm3ys2yzd83zcngcpzlnw0000gn/T/easy_install-rn886pfq/numpy-1.16.2/setup.py", line 415, in <module>
  File "/var/folders/kv/1wctm3ys2yzd83zcngcpzlnw0000gn/T/easy_install-rn886pfq/numpy-1.16.2/setup.py", line 407, in setup_package
  File "/var/folders/kv/1wctm3ys2yzd83zcngcpzlnw0000gn/T/easy_install-rn886pfq/numpy-1.16.2/numpy/distutils/core.py", line 171, in setup
  File "/usr/local/Cellar/pypy3/7.0.0/libexec/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/usr/local/Cellar/pypy3/7.0.0/libexec/lib-python/3/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/local/Cellar/pypy3/7.0.0/libexec/lib-python/3/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/local/Cellar/pypy3/7.0.0/libexec/lib-python/3/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/local/Cellar/pypy3/7.0.0/libexec/site-packages/setuptools/command/bdist_egg.py", line 163, in run
    self.run_command("egg_info")
  File "/usr/local/Cellar/pypy3/7.0.0/libexec/lib-python/3/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/local/Cellar/pypy3/7.0.0/libexec/lib-python/3/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/var/folders/kv/1wctm3ys2yzd83zcngcpzlnw0000gn/T/easy_install-rn886pfq/numpy-1.16.2/numpy/distutils/command/egg_info.py", line 26, in run
  File "/usr/local/Cellar/pypy3/7.0.0/libexec/lib-python/3/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/local/Cellar/pypy3/7.0.0/libexec/lib-python/3/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/var/folders/kv/1wctm3ys2yzd83zcngcpzlnw0000gn/T/easy_install-rn886pfq/numpy-1.16.2/numpy/distutils/command/build_src.py", line 148, in run
  File "/var/folders/kv/1wctm3ys2yzd83zcngcpzlnw0000gn/T/easy_install-rn886pfq/numpy-1.16.2/numpy/distutils/command/build_src.py", line 159, in build_sources
  File "/var/folders/kv/1wctm3ys2yzd83zcngcpzlnw0000gn/T/easy_install-rn886pfq/numpy-1.16.2/numpy/distutils/command/build_src.py", line 292, in build_library_sources
  File "/var/folders/kv/1wctm3ys2yzd83zcngcpzlnw0000gn/T/easy_install-rn886pfq/numpy-1.16.2/numpy/distutils/command/build_src.py", line 375, in generate_sources
  File "numpy/core/setup.py", line 667, in get_mathlib_info
RuntimeError: Broken toolchain: cannot link a simple C program

**Comment by jonchang** [comment]
[Per the install instructions](https://github.com/jonchang/tact#installation), I do not support installing TACT via `pip`. If you want to use `pip` anyway you will have to figure out the installation on your own. I'll also note that this is an issue more properly filed with scipy or numpy since it is their packages that are failing.

As you are already using Homebrew, please run `brew install jonchang/biology/tact` instead.

Note that since the manuscript hasn't been published, I don't recommend using this for research until the paper has been accepted.

**Comment by Cactusolo** [comment]
> [Per the install instructions](https://github.com/jonchang/tact#installation), I do not support installing TACT via `pip`. If you want to use `pip` anyway you will have to figure out the installation on your own. I'll also note that this is an issue more properly filed with scipy or numpy since it is their packages that are failing.
> 
> As you are already using Homebrew, please run `brew install jonchang/biology/tact` instead.
> 
> Note that since the manuscript hasn't been published, I don't recommend using this for research until the paper has been accepted.

Understood!! All my best to you and your paper!

Thanks!

Miao
